kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: chluehr/b2-backup
    tags:
      - latest
    username: 
        from_secret: docker_username
    password: 
        from_secret: docker_password


